# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/santos10-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter santos103g santos10wifi santos10lte,$(TARGET_DEVICE)),)

endif
